services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=userdb,datadb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    ports:
      - "5432:5432"

  user-service:
    build:
      context: ./backend/user_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend/user_service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/userdb
    depends_on:
      - db
    restart: unless-stopped

  data-service:
    build:
      context: ./backend/data_service
    ports:
      - "8001:8001"
    volumes:
      - ./backend/data_service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/datadb
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - user-service
      - data-service
    environment:
      - VITE_USER_SERVICE_URL=http://localhost:8000
      - VITE_DATA_SERVICE_URL=http://localhost:8001
    restart: unless-stopped

volumes:
  postgres_data: